services:
  redis_broker:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  dataset-service:
    build:
      context: .
      dockerfile: services/dataset_operations_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    volumes:
      - C:/Users/hmark/Documents/Datasets/datasets:/app/datasets
      - D:/storage/lion17:/app/storage

  fcnn-api:
    build:
      context: .
      dockerfile: services/fcnn_service/Dockerfile
    ports:
      - "8001:8001"
    command: uvicorn services.fcnn_service.main:app --host 0.0.0.0 --port 8001
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/0
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
    volumes:
      - C:/Users/hmark/Documents/Datasets/datasets:/app/datasets
      - D:/storage/lion17:/app/storage

  fcnn-worker:
    build:
      context: .
      dockerfile: services/fcnn_service/Dockerfile
    command: celery -A services.fcnn_service.tasks.celery_app worker --loglevel=info -P solo
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/0
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
      - fcnn-api
    volumes:
      - C:/Users/hmark/Documents/Datasets/datasets:/app/datasets
      - D:/storage/lion17:/app/storage