services:
  redis_broker:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  dataset-service:
    build:
      context: .
      dockerfile: services/dataset_operations_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
      - GDRIVE_DATASET_URL=https://drive.google.com/uc?id=1Fe3DjPOGgzNmlnJj0yn0WTUazh3ojL8k
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage

  fcnn-api:
    build:
      context: .
      dockerfile: services/fcnn_service/Dockerfile
    ports:
      - "8001:8001"
    command: uvicorn services.fcnn_service.main:app --host 0.0.0.0 --port 8001
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/1
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/1
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage

  fcnn-worker:
    build:
      context: .
      dockerfile: services/fcnn_service/Dockerfile
    command: celery -A services.fcnn_service.tasks.celery_app worker --loglevel=info -P solo
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/1
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/1
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
      - fcnn-api
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage
    shm_size: '2gb'

  helm-api:
    build:
      context: .
      dockerfile: services/helm_service/Dockerfile
    ports:
      - "8002:8002"
    command: uvicorn services.helm_service.main:app --host 0.0.0.0 --port 8002
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/2
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/2
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage

  helm-worker:
    build:
      context: .
      dockerfile: services/helm_service/Dockerfile
    command: celery -A services.helm_service.tasks.celery_app worker --loglevel=info -P solo
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/2
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/2
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
      - OMP_NUM_THREADS=4
      - OPENBLAS_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - NUMEXPR_NUM_THREADS=4
    depends_on:
      - redis_broker
      - helm-api
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage

  dev-drnn-api:
    build:
      context: .
      dockerfile: services/dev_drnn_service/Dockerfile
    ports:
      - "8003:8003"
    command: uvicorn services.dev_drnn_service.main:app --host 0.0.0.0 --port 8003
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/3
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/3
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage

  dev-drnn-worker:
    build:
      context: .
      dockerfile: services/dev_drnn_service/Dockerfile
    command: celery -A services.dev_drnn_service.tasks.celery_app worker --loglevel=info -P solo
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/3
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/3
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
      - dev-drnn-api
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage

  dev-drnn-aux-api:
    build:
      context: .
      dockerfile: services/dev_drnn_aux_service/Dockerfile
    ports:
      - "8004:8004"
    command: uvicorn services.dev_drnn_aux_service.main:app --host 0.0.0.0 --port 8004
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/4
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/4
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage

  dev-drnn-aux-worker:
    build:
      context: .
      dockerfile: services/dev_drnn_aux_service/Dockerfile
    command: celery -A services.dev_drnn_aux_service.tasks.celery_app worker --loglevel=info -P solo
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/4
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/4
      - PROJECT_ROOT=/app
      - DATASET_ROOT=/app/datasets
      - STORAGE_ROOT=/app/storage
    depends_on:
      - redis_broker
      - dev-drnn-aux-api
    volumes:
      - ./datasets:/app/datasets
      - ./storage:/app/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development